version: '3'
services:
  web:
    image: ditsara/sinatra-demo:development
    build:
      context: .
    ports:
      - "4567:4567"
    volumes:
      - .:/app:cached
      - gems:/gems
    working_dir: /app
    command: ./server.rb

volumes:
  gems:
